from io import StringIO
import sys
import contextlib
import pandas as pd

@contextlib.contextmanager
def capture_stdout():
    old_stdout = sys.stdout
    stdout_buffer = StringIO()
    sys.stdout = stdout_buffer
    try:
        yield stdout_buffer
    finally:
        sys.stdout = old_stdout

def execute_and_augment(generated_code, df, row_map, col_map, target_column=None):
    """
    Executes the Pandas code generated by the LLM safely (mock safety) and 
    reverse lookups the mapped excel coordinates.
    """
    # 1. Execute the LLM's Pandas code
    # WARNING: In production, heavily sandbox this execution!
    exec_globals = {"pd": pd, "df": df.copy()}
    
    with capture_stdout() as output:
        try:
            exec(generated_code, exec_globals)
        except Exception as e:
            print(f"Error executing LLM code: {e}")
            return None, None
        
    result_str = output.getvalue().strip()
    
    try:
        import re
        # We look at the last line of the LLM's printed output
        last_line = result_str.split('\n')[-1].strip()
        try:
            df_index = int(last_line)
        except ValueError:
            # If the LLM printed something like 'Index([5], dtype=...)' or '5.'
            match = re.search(r'\b\d+\b', last_line)
            if match:
                df_index = int(match.group())
            else:
                raise ValueError("No integer found in output")
        
        # 2. Look up the original Excel coordinates
        excel_sheet = row_map[df_index]["sheet"]
        excel_row = row_map[df_index]["excel_row"]
        
        # 3. Augment the Answer
        if target_column and target_column in col_map:
            answer_val = df.loc[df_index, target_column]
            excel_col_letter = col_map[target_column]["excel_col_letter"]
            source_citation = f"Sheet '{excel_sheet}', Row {excel_row}, Col {excel_col_letter}"
        else:
            # Fallback if no specific column is requested
            answer_val = df.loc[df_index].to_dict()
            source_citation = f"Sheet '{excel_sheet}', Row {excel_row}"
        
        return answer_val, source_citation
        
    except Exception as e:
        print(f"Could not parse the expected DataFrame index from the LLM code output: {e}")
        print("Raw LLM output:\n", result_str)
        return None, None
